######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 2 13:40:28 2018
######################################################################

TEMPLATE = app
TARGET = imdemo.app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Imcontext.hpp
SOURCES += main.cpp

QMAKE_RPATHDIR += /usr/lib/boeye 
LIBS += /usr/lib/boeye/libboeyeim.so.1 \
        /usr/lib/boeye/libboeyewidget.so.1 \
        /usr/lib/boeye/libguobi.so.0
