######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 16:57:52 2018
######################################################################

TEMPLATE = app
TARGET = first.app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digma_hw.h
SOURCES += firstapp.cpp digma_hw.c
